;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        beginning-of-visual-line
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        downcase-region
        electric-pair-delete-pair
        end-of-visual-line
        forward-sexp
        helm-smex
        ido-find-file
        indent-for-tab-command
        indent-rigidly
        isearch-abort
        isearch-backward-regexp
        isearch-exit
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        message-beginning-of-line
        subword-left
        subword-right
        ))

(setq mc/cmds-to-run-once
      '(
        comment-region
        helm-maybe-exit-minibuffer
        isearch-delete-char
        next-buffer
        smex
        ))
